// Module included in the following assemblies:
//
// * documentation/doc-installing-and-using-tackle/master.adoc

[id='importing-applications_{context}']
= Importing applications

You can import multiple applications into the *Application Inventory* page of the {project-name} web console by using a CSV file.

[NOTE]
====
You cannot create tags or business services by importing a CSV file.
====

The CSV file must contain the following fields:

* `Record Type 1`: Required field. The value must be `1`.
* `Application Name`: Required field.
* `Description`: Optional.
* `Comments`: Optional.
* `Business Service`: Optional.
* `Tag Type 1`: Optional unless you are creating a tag.
* `Tag 1`: Optional. If you create a tag, it must have a corresponding `Tag Type`.
+
You can create `Tag Type <number>` and `Tag <number>` fields for additional tags.

.Prerequisites

* If you specify values for the business service, tag, or tag type columns, the values must be created by using the *Controls* page of the {project-name} web console.

.Procedure

. Click *Application Inventory*.
. Click the {kebab} in the toolbar and select *Import*.
. Browse to the CSV file and click *Open*.
. Click *Import*.
+
The imported applications are displayed in the Application Inventory.
