// Module included in the following assemblies:
//
// * documentation/doc-installing-and-using-tackle/master.adoc

[id="starting-assessment_{context}"]
= Starting an assessment

You can start an application assessment in the *Application Inventory* page of the {project-name} web console.

.Prerequisites

* You must have an application in the *Application Inventory* page with the *Assessment* status, *Not started*.

.Procedure

. Select an application that has not been assessed and click the *Assess* button in the toolbar.
. Select individual stakeholders or stakeholder groups and then click *Next*.
. Select responses to questions on each page of the *Application assessment* wizard and then click *Next*.
+
[NOTE]
====
All questions are mandatory.
====

. When you have completed all the responses, click *Save* to save the assessment or *Save and review* to start the assessment review process.
+
The *Assessment* status of the application in the *Application Inventory* page is *Completed*.
