// Module included in the following assemblies:
//
// * documentation/doc-installing-and-using-tackle/master.adoc

:_content-type: CONCEPT
[id="about-pathfinder_{context}"]
= About {project-name}

ifeval::["{build}" == "downstream"]
{project-name} is a cloud-native application that assesses your applications to determine an appropriate migration strategy for each application, for example, rehosting, replatforming, or refactoring. {project-name} also helps you to plan the migration of your applications to {ocp}.
endif::[]
ifeval::["{build}" == "upstream"]
{project-name} is a cloud-native application that assesses your applications to determine an appropriate migration strategy for each application, for example, rehosting, replatforming, or refactoring. {project-name} also helps you to plan the migration of your applications to an enterprise Kubernetes platform.
endif::[]

{project-name} uses an interactive questionnaire for the assessment. The assessment process enables key stakeholders to gather information about applications, to discuss risks flagged by {project-name}, and to reach a consensus in formulating recommendations for each application.
