// Module included in the following assemblies:
//
// * documentation/doc-installing-and-using-tackle/master.adoc

:_content-type: PROCEDURE
[id="accessing-console_{context}"]
= Logging in to the {project-name} web console

You can log in to the {project-name} web console.

.Prerequisites

* You must have the {project-name} application installed.

.Procedure

ifeval::["{build}" == "upstream"]
. In the Kubernetes dashboard, click *Services* -> *Ingresses*.
. Click the *Endpoint* of the `tackle-sample` ingress to launch the {project-name} web console in a new browser window.
endif::[]
ifeval::["{build}" == "downstream"]
. In the {ocp} web console, click *Workloads* -> *Pods*.
. Click the `tackle-ui` pod to view its route.
. Click the route to launch the {project-name} web console in a new browser window.
endif::[]
. Enter `tackle` in the *Username or email* field, `password` in the *Password* field, and click *Log in*.

[IMPORTANT]
====
You must change the default password of the tackle user.
====
