// Module included in the following assemblies:
//
// * documentation/doc-installing-and-using-tackle/master.adoc

[id="console services_{context}"]
= {project-name} web console services

{project-name} web console provides the following services:

* Application inventory
* Assessments
* Reviews
* Reports
* Controls

[id="application-inventory_{context}"]
== Application inventory

The *Application inventory* page enables you to perform the following tasks:

* Manage your application portfolio.
* Define and manage application dependencies.
* Link applications to the business services that they support.
* Describe and categorize applications by using tags.

[id="assessments_{context}"]
== Assessments

You can assess your applications on the *Application inventory* page.

The assessment helps you determine an appropriate migration strategy for each application, for example, rehosting, replatforming, or refactoring.

The assessment is an interactive questionnaire that gathers information and identifies possible risks and their severity.

[id="reviews_{context}"]
== Reviews

You can review a completed assessment on the *Application inventory* page.

The following information is collected from each reviewer:

* *Proposed action*: Proposed action for the application, for example, replatforming or rehosting.
* *Effort estimate*: How much effort is involved in migrating the application, based on the proposed action and the identified risks.
* *Business criticality*: How critical the application is to your business on a scale of `1` to `10`.
* *Work priority*: Your work priority estimate for the proposed action on a scale of `1` to `10`.

The *Reports* page displays the results of the reviews.

[id="reports_{context}"]
== Reports

The *Reports* page displays the results of the application assessments and reviews and can help you to plan your migration.

The reports provide information about the following:

* Suitability of applications for containerization.
* Possible risks and severity.
* Adoption plan based on estimated effort, work priority, and application dependencies.

[id="controls_{context}"]
== Controls

The *Controls* page enables you to manage the following entities:

* *Stakeholder*: A stakeholder is an individual with an interest in an application or a subject matter expert.
* *Stakeholder group*: A stakeholder group is a group of related stakeholders. A stakeholder can belong to one or more stakeholder groups. Stakeholder groups are used to assign multiple stakeholders to review an assessment.
* *Job function*: A job function is an attribute of a stakeholder. You use a predefined job function or create a new job function.
* *Business service*: A business service is an attribute of an application, for example, credit card service, transportation, or IT support. You can use a predefined business service or create a new business service.
* *Tag*: A tag is an attribute of an application. Tags are an extensible and flexible way to add metadata to applications. Tags are grouped under a parent tag type. You can use a predefined tag or create a new tag.
* *Tag type*: A tag type defines the rank and background color of a group of related tags.
