// Module included in the following assemblies:
//
// * documentation/doc-installing-and-using-tackle/master.adoc

:_content-type: PROCEDURE
[id="creating-stakeholder_{context}"]
= Creating a stakeholder

You can create a stakeholder on the *Controls* page of the {project-name} web console.

.Prerequisites

* The stakeholder must have a valid email address.

.Procedure

. In the {project-name} web console, click *Controls*.
. Click the *Stakeholders* tab and then click *Create new*.
. Complete the following fields:

* *Email*: Email address of the stakeholder.
* *Display name*: Name of the stakeholder.
* *Job function*: Optional. You can select a predefined job function or type a job function to create it.
* *Groups*: Optional. You can select one or more stakeholder groups from a list of stakeholder groups that you have created.

. Click *Create*.
+
The new stakeholder is displayed on the *Stakeholders* tab.

. Expand the stakeholder to view the stakeholder groups to which the stakeholder belongs.
