// Module included in the following assemblies:
//
// * documentation/doc-installing-and-using-tackle/master.adoc

[id='importing-applications_{context}']
= Importing applications

You can import multiple applications into the *Application inventory* page of the {project-name} web console by using a CSV file.

[NOTE]
====
You cannot create tags or business services by importing a CSV file.
====

The CSV file must contain the following fields:

* `Record Type 1`: Required field. The value must be `1`.
* `Application Name`: Required field.
* `Description`: Can have a `null` value.
* `Comments`: Can have a `null` value.
* `Business Service`: Can have a `null` value.
* `Tag Type 1`: Can have a `null` value.
* `Tag 1`: Can have a `null` value.
+
You can create `Tag Type <number>` and `Tag <number>` fields for additional tags.

.Prerequisites

* You must create a CSV file.
+
If you specify values for the business service, tag, or tag type columns, the values must exist in the *Controls*.

.Procedure

. In the {project-name} web console, click *Application inventory*.
. Click the {kebab} in the toolbar and select *Import*.
. Browse to the CSV file and click *Open*.
. Click *Import*.
+
The imported applications are displayed in the Application Inventory.
