// Module included in the following assemblies:
//
// * documentation/doc-installing-and-using-tackle/master.adoc

[id="installing-operator_{context}"]
= Installing the {operator}

ifeval::["{build}" == "downstream"]
[NOTE]
====
The {operator} is a Community Operator. Red Hat provides no support for Community Operators.
====

You install the {operator} on an {ocp} cluster by using Operator Lifecycle Manager.

.Prerequisites

* You must have {ocp} 4 installed.
* You must have `cluster-admin` privileges.

.Procedure

. In the {ocp} web console, click *Operators* -> *OperatorHub*.
. Click the *Modernization & Migration* category and then click the *{operator}* tile.
. Click *Install*.
. Click *Install* to install the Operator in the +{namespace}+ namespace.
endif::[]
ifeval::["{build}" == "upstream"]
You download and install the {operator} on an {ocp} cluster.

.Prerequisites

* You must have `cluster-admin` privileges.

.Procedure

. Install the {operator}:
+
[source,terminal,subs="attributes+"]
----
$ {oc} create -f https://operatorhub.io/install/tackle-operator.yaml
----
+
The {operator} is installed in the +{namespace}+ namespace by default.
endif::[]

. Verify the {operator} installation by viewing its resources:
+
[source,terminal,subs="attributes+"]
----
$ {oc} get all -n {namespace}
----
