// Module included in the following assemblies:
//
// * documentation/doc-installing-and-using-tackle/master.adoc

[id="installing-pathfinder_{context}"]
= Installing {project-name}

You install the {operator} on the cluster and then install the {project-name} application in a project.

ifeval::["{build}" == "downstream"]
[NOTE]
====
The {operator} is a Community Operator. Red Hat provides no support for Community Operators.
====

[id="installing-operator_{context}"]
== Installing the Tackle Operator

You install the {operator} by using the OpenShift web console.

.Prerequisites

* You must have `cluster-admin` privileges.

.Procedure

. In the OpenShift web console, click *Operators* -> *OperatorHub*.
. Click the *Modernization & Migration* category and then click the *{operator}* tile.
. Click *Install*.
. Select a project from the *Installed Namespace* list and click *Install*.
. After the {operator} is installed, click *View Operator* to verify the installation.

[id="installing-application_{context}"]
== Installing the {project-name} application

You install the {project-name} application in a project by using the OpenShift web console.

After you have installed the application, you can log in to the {project-name} web console.

.Prerequisites

* The {operator} must be installed on the cluster.
* You must have `project-admin-user` privileges.
* You must create a project for {project-name}.

.Procedure

. In the OpenShift web console, switch to the *Developer* perspective and click *+Add*.
. In the *Add* view, click *Operator Backed*.
. Click the *Tackle by Konveyor* tile.
. Click *Create*.
. Review the application settings and click *Create*.
. Click *Topology*.
. Click the *OpenURL* icon of the `tackle-ui` pod to open the {project-name} application in a new browser window.
endif::[]
ifeval::["{build}" == "upstream"]
.Prerequisites

* You must have `admin` privileges to install the {operator}.
* You must have `project-admin` privileges to install the {project-name} application in a project.

.Procedure

. Navigate to link:https://operatorhub.io[operatorhub.io].
. Enter `Tackle` in the Search field to locate the {operator}.
. Click the *{operator}* tile and then click *Install*.
. Follow the installation instructions.
. Install the {project-name} application in a project by following the procedure for your enterprise Kubernetes platform.
. Obtain the route or URL of the `tackle-ui` pod to open the {project-name} application in a new browser window.
endif::[]
. Enter your *Username or email* and *Password* and then click *Log in* to access the {project-name} web console.
