// Module included in the following assemblies:
//
// * documentation/doc-installing-and-using-tackle/master.adoc

[id="installing-tackle-application_{context}"]
= Installing the {project-name} application

ifeval::["{build}" == "downstream"]
You install {project-name} in a project by using the {ocp} web console.

.Prerequisites

* The {operator} must be installed on an {ocp} cluster.
* You must have `project-admin-user` privileges.

.Procedure

. Click *Operators* -> *Installed Operators* and select the {operator}.
. Under *Provided APIs*, click *Create instance* on the Tackle Toolkit card.
. Click *Workloads* -> *Deployments* in your project to verify the installation.
endif::[]
ifeval::["{build}" == "upstream"]
You install {project-name} in a namespace by creating an instance of the {project-name} application.

.Prerequisites

* The {operator} must be installed on the cluster.
* You must have `project-admin` privileges.

.Procedure

. Create an instance of the {project-name} application, specifying its namespace:
+
[source,terminal,subs="attributes+"]
----
$ {oc} apply -n <namespace> -f https://raw.githubusercontent.com/konveyor/tackle-operator/main/src/main/resources/k8s/tackle/tackle.yaml
----
+
[NOTE]
====
You can create multiple instances of the {project-name} application in the same namespace by specifying a unique name for each instance in the `tackle.yaml` file.
====

. In the Kubernetes dashboard, click *Workloads* -> *Deployments* to verify the installation.
endif::[]
