// Module included in the following assemblies:
//
// * documentation/doc-installing-and-using-tackle/master.adoc

[id="installing-application_{context}"]
= Installing the {project-name} application

ifeval::["{build}" == "downstream"]
Install the {project-name} application in a project by using the {ocp} web console.

After you have installed the application, you can log in to the {project-name} web console.

.Prerequisites

* The {operator} must be installed on the cluster.
* You must have `project-admin-user` privileges.
* You must create a project for {project-name}.

.Procedure

. In the {ocp} web console, switch to the *Developer* perspective and click *+Add*.
. In the *Add* view, click *Operator Backed*.
. Click the *Tackle by Konveyor* tile.
. Click *Create*.
. Review the application settings and click *Create*.
. Click *Topology*.
. Click the *OpenURL* icon of the `tackle-ui` pod to open the {project-name} web console in a new browser window.
endif::[]
ifeval::["{build}" == "upstream"]
Install the {project-name} application in a project.

.Prerequisites

* The {operator} must be installed on the cluster.
* You must have `project-admin` privileges to install the {project-name} application in a project.
* You must create a project for {project-name}.

.Procedure

. Install the {project-name} application in a project by following the procedure for your enterprise Kubernetes platform.
. Obtain the route or URL of the `tackle-ui` pod and record it. This is the URL of the {project-name} web console
endif::[]
