// Module included in the following assemblies:
//
// * documentation/doc-installing-and-using-tackle/master.adoc

[id="reviewing-assessment_{context}"]
= Reviewing an assessment

You review an application assessment on the *Application inventory* page of the {project-name} web console.

.Prerequisites

* An application must have a *Completed* assessment status and a *Not started* review status.

.Procedure

. In the {project-name} web console, click *Application inventory*.
. Select an application with a *Completed* assessment status and a *Not started* review status and click the *Review* button in the toolbar.
. Review the assessment in the *Assessment summary* section on the *Review* page.
+
The *Assessment summary* table contains a *Risk* column that indicates the severity of the risk associated with each response.

. Select a *Proposed action* and an *Effort estimate*.
. Set values for *Business criticality* and *Work priority*.
. Optional: Enter comments in the *Comments* field.
. Click *Submit review*.
+
The *Review* status of each application is *Completed*.

. Expand the application to view the review results.
