// Module included in the following assemblies:
//
// * documentation/doc-installing-and-using-tackle/master.adoc

[id="upgrading_{context}"]
= Upgrading the {project-name} application

You can manually upgrade the {project-name} application from 1.0.0 to 1.1.0.

.Prerequisites

* You must have `project-admin-user` privileges.

.Procedure

. Update the `tackle-keycloak` deployment:
+
[source,terminal,subs="attributes+"]
----
$ {oc} -n <namespace> exec deployments/tackle-keycloak -c tackle-keycloak -- bash -c '/opt/jboss/keycloak/bin/kcadm.sh update realms/tackle -s internationalizationEnabled=true -s supportedLocales+=en -s supportedLocales+=es -s defaultLocale=en --server http://localhost:8080/auth --realm master --user $KEYCLOAK_USER --password $KEYCLOAK_PASSWORD' <1>
----
<1> Specify the namespace in which you installed the {project-name} application.

. Update the `tackle-application-inventory-rest` deployment:
+
[source,terminal,subs="attributes+"]
----
$ {oc} set image -n <namespace> deployment/tackle-application-inventory-rest tackle-application-inventory-rest=quay.io/konveyor/tackle-application-inventory:1.1.0-native
----

. Update the `tackle-controls-rest` deployment:
+
[source,terminal,subs="attributes+"]
----
$ {oc} set image -n <namespace> deployment/tackle-controls-rest tackle-controls-rest=quay.io/konveyor/tackle-controls:1.1.0-native
----

. Update the `tackle-pathfinder-rest` deployment:
+
[source,terminal,subs="attributes+"]
----
$ {oc} set image -n <namespace> deployment/tackle-pathfinder-rest tackle-pathfinder-rest=quay.io/konveyor/tackle-pathfinder:1.1.0-native
----

. Update the `tackle-ui` deployment:
+
[source,terminal,subs="attributes+"]
----
$ {oc} set image -n <namespace> deployment/tackle-ui tackle-ui=quay.io/konveyor/tackle-ui:1.1.0
----

. Log in to the web console and click the Help icon beside the user name to verify the upgrade.
+
The *About {project-name}* window opens and displays the version number.
