// common document attributes
include::modules/common-attributes.adoc[]
ifeval::["{build}" == "downstream"]
= {title}
endif::[]
ifeval::["{build}" == "upstream"]
= {title} ({project-version})
endif::[]
:toc:
:toc-title:
:toclevels: 3
:compat-mode:
:context: pathfinder

ifeval::["{build}" == "downstream"]
include::modules/making-open-source-more-inclusive.adoc[]
endif::[]

{the} {project-first} is a cloud-native application that assesses your applications to gauge whether the applications are suitable for rehosting on {ocp}.

{project-short} uses an interactive questionnaire for the assessment. The assessment process enables key stakeholders, led by a Solution Architect, to gather information about applications, to discuss risks that {project-short} might flag, and to reach a consensus in formulating recommendations for each application.

{project-short} provides the following services in a web console:

* Controls: Manages data describing applications and stakeholders, for example, job function, business service, stakeholder
* Application inventory: Manages the application portfolio and groups the applications for analysis or assessment
* Reports: Displays the assessments and reviews for applications in the application inventory. The reports are dynamic and can display results for applications grouped by filters.

include::modules/about-pathfinder.adoc[leveloffset=+1]
include::modules/installing-pathfinder.adoc[leveloffset=+1]
