// common document attributes
include::modules/common-attributes.adoc[]
ifeval::["{build}" == "downstream"]
= {title}
endif::[]
ifeval::["{build}" == "upstream"]
= {title} ({project-version})
endif::[]
:toc:
:toc-title:
:toclevels: 3
:compat-mode:
:context: pathfinder

ifeval::["{build}" == "downstream"]
include::modules/making-open-source-more-inclusive.adoc[]
endif::[]

{the} {project-first} is a cloud-native application that assesses your applications to gauge whether the applications are suitable for rehosting on {ocp}.

{project-short} uses an interactive questionnaire for the assessment. The assessment process enables key stakeholders, led by a Solution Architect, to gather information about applications, discuss any risks that {project-short} flags, and to reach a consensus in formulating recommendations for each application.

include::modules/about-pathfinder.adoc[leveloffset=+1]
include::modules/installing-pathfinder.adoc[leveloffset=+1]

[id="managing-stakeholders-job-functions-business-services-and-tags_{context}"]
== Managing stakeholders, job functions, business services, and tags

You can manage the following data in the *Controls* page of the {project-full} web console:

* Stakeholders: Individuals with an interest in the applications or subject matter experts who can contribute to the application assessment.
+
A stakeholder can be the owner of a business service.
* Stakeholder groups: Groups of related stakeholders.
+
A stakeholder can belong to one or more stakeholder groups.
* Job functions: Attribute of a stakeholder.
+
You can define new job functions or use predefined job functions, for example, Business Analyst or Program Manager.
* Business services: Attribute of an application, for example, credit card service, transportation, or IT support.
+
A business service is owned by a stakeholder.
* Tags: Attribute of an application and is used for creating filters and searches.
+
A tag is associated with a tag type that determines its display rank and color.

include::modules/creating-stakeholder.adoc[leveloffset=+2]
include::modules/creating-stakeholder-group.adoc[leveloffset=+2]
include::modules/creating-business-service.adoc[leveloffset=+2]
include::modules/creating-tag-type.adoc[leveloffset=+2]
include::modules/creating-tag.adoc[leveloffset=+2]

[id="managing-applications_{context}"]
== Managing applications

You can manage your application portfolio in the *Application Inventory* page of the {project-full} web console.

include::modules/creating-application.adoc[leveloffset=+2]
include::modules/tagging-applications.adoc[leveloffset=+2]
include::modules/adding-business-service-to-applications.adoc[leveloffset=+2]
include::modules/managing-application-dependencies.adoc[leveloffset=+2]
