// common document attributes
include::modules/common-attributes.adoc[]
ifeval::["{build}" == "downstream"]
= {title}
endif::[]
ifeval::["{build}" == "upstream"]
= {title} (draft)
endif::[]
:toc:
:toc-title:
:toclevels: 3
:compat-mode:
:context: pathfinder

ifeval::["{build}" == "downstream"]
include::modules/making-open-source-more-inclusive.adoc[]
endif::[]

include::modules/about-pathfinder.adoc[]
include::modules/installing-pathfinder.adoc[]

[id="managing-stakeholders-job-functions-business-services-and-tags_{context}"]
== Managing the Controls

The *Controls* page of the {project-name} web console enables you to manage the following:

Stakeholder::
Individual with an interest in an application or a subject matter expert. Stakeholders are contributors to the application assessment process.

Stakeholder group::
Group of related stakeholders. A stakeholder can belong to one or more stakeholder groups. Stakeholder groups are used to assign multiple stakeholders to review an assessment.

Job function::
Attribute of a stakeholder. You can define a new job function or use predefined job functions, for example, Business Analyst or Program Manager.

Business service::
Attribute of an application, for example, credit card service, transportation, or IT support. A business service is owned by a stakeholder.

Tag::
Attribute of an application. Tags are used for creating filters and searches. Each tag is associated with a _tag type_ that determines its display rank and color and enables you to group related tags.

include::modules/creating-stakeholder.adoc[leveloffset=+2]
include::modules/creating-stakeholder-group.adoc[leveloffset=+2]
include::modules/creating-business-service.adoc[leveloffset=+2]
include::modules/creating-tag-type.adoc[leveloffset=+2]
include::modules/creating-tag.adoc[leveloffset=+2]

[id="managing-applications_{context}"]
== Managing the Application Inventory

You can manage your application portfolio in the *Application Inventory* page of the {project-name} web console.

include::modules/creating-application.adoc[leveloffset=+2]
include::modules/importing-applications.adoc[leveloffset=+2]
include::modules/tagging-applications.adoc[leveloffset=+2]
include::modules/adding-business-service-to-applications.adoc[leveloffset=+2]
include::modules/managing-application-dependencies.adoc[leveloffset=+2]
